add mothod export segmentation
fastlabel/fastlabel-python-sdk pull request #146
Opened 2023-04-12 06:59 UTC by Akkiy3314

#145 
export_semantic_segmentationのメソッドにclassesとstart_indexを追加

https://user-images.githubusercontent.com/114887968/231376775-1db17acc-e1da-43c3-8e62-2c7f9fccda7f.mov

2023-04-13 14:21 UTC, ShuheiUchida commented on fastlabel/__init__.py
> +        classes is fix classes list (Optional).
どんな使い方をするためのものなのかもう少し補足お願いしますー

2023-04-13 14:35 UTC, ShuheiUchida commented on fastlabel/__init__.py
> +        target_classes = classes
以下の形の方がシンプルだと思いましたー
```
      if len(classes) == 0:
            for task in tasks:
                for annotation in task["annotations"]:
                    classes.append(annotation["value"])
            classes = list(set(classes))
            classes.sort()
```

2023-04-13 14:36 UTC, ShuheiUchida commented on fastlabel/__init__.py
> +        start_index: int = 1,
export_instance_segmentation側にもstart_indexは足してください。
ローカルでのテストも忘れずにお願いします。

2023-04-14 04:47 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        classes is fix classes list (Optional).
コメント追加しました。
(英語自信ないですが...)

2023-04-14 04:47 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        start_index is color pallet start index (Optional).
提案ありがとうございます。
修正しました!

2023-04-14 04:47 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        target_classes = classes
こちら修正しました!
SQLのファンクションが頭にこびりついてましたね...

2023-04-14 04:47 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        start_index: int = 1,
追加しました!
動作確認通ること確認しています。
![スクリーンショット 2023-04-14 13 37 03](https://user-images.githubusercontent.com/114887968/231943627-d4920c5f-4729-4cd2-9d2f-ad9a9c0df3c9.png)

2023-04-14 04:48 UTC, Akkiy3314 commented
@ShuheiUchida 
レビュー箇所修正したので
お手数をおかけしますが確認お願い致します。

2023-04-14 07:01 UTC, ShuheiUchida requested changes
確認お願いします！

2023-04-14 07:01 UTC, ShuheiUchida commented on fastlabel/__init__.py
> +        classes: List = [],
instance_segmentationではclassは使いませんー！

2023-04-14 08:16 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        classes: List = [],
削除しました!

2023-04-14 08:29 UTC, ShuheiUchida submitted a review, later dismissed
LGTM!!

2023-04-14 08:30 UTC, ShuheiUchida commented
@ueno-k-work @ryoKaz 
コード確認済みです！
マージの運用がわかっておらず
この後お願いできますでしょうか？

2023-04-18 09:58 UTC, Akkiy3314 commented
@takahiro-tamenishi 
こちらstart_index修正したので確認お願い致します!

2023-04-18 10:34 UTC, takahiro-tamenishi reviewed
@Akkiy3314 
コメントしました！

2023-04-18 10:51 UTC, Akkiy3314 commented on fastlabel/__init__.py
> +        start_index is the first index of color index corresponding to color pallete (Optional).
すみません、、コメント修正漏れてました、、
指摘内容で修正しました!
ありがとうございます🙇

2023-04-18 10:53 UTC, takahiro-tamenishi approved these changes
LGTM！

2023-04-18 10:54 UTC, merged