WIP: update to 0.3.0
fastlabel/fastlabel-python-sdk pull request #9
Opened 2021-02-22 11:08 UTC by faycute

2021-02-22 11:13 UTC, eisuke-ueta requested changes

2021-02-22 11:13 UTC, eisuke-ueta commented on fastlabel/__init__.py
> +FASTLABEL_ENDPOINT = "http://localhost:4000/v1/"
ローカルじゃなくて、本番環境の方を向けるの忘れずに。

2021-02-22 11:13 UTC, eisuke-ueta commented on fastlabel/__init__.py
> +    def __base64_encode(self, file_path: str) -> str:
これアンスコ2個ない？

2021-02-22 11:13 UTC, eisuke-ueta commented on fastlabel/__init__.py
> +    def __is_supported_ext(self, file_path: str) -> bool:
ここも

2021-02-22 11:47 UTC, faycute commented on fastlabel/__init__.py
> +    def __base64_encode(self, file_path: str) -> str:
アンスコ2個でprivateらしいよ？あれ？

2021-02-22 11:55 UTC, faycute commented on fastlabel/__init__.py
> +FASTLABEL_ENDPOINT = "http://localhost:4000/v1/"
後でドキュメントまとめた時に変えるね〜

2021-02-22 13:10 UTC, eisuke-ueta commented on fastlabel/__init__.py
> +    def __base64_encode(self, file_path: str) -> str:
えっ、そうなん？知らんかった。笑 じゃあこのままでOKっす。

2021-02-23 02:40 UTC, faycute commented
ドキュメントを更新したので確認お願い！
915ebc8

2021-02-24 01:08 UTC, eisuke-ueta approved these changes

2021-02-24 01:09 UTC, merged